// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eizcqhhwvephmrfxtghw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpemNxaGh3dmVwaG1yZnh0Z2h3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NjIwNzMsImV4cCI6MjA2NTIzODA3M30.widSLABErkrBqge1o9cK4oSVdXNbDe7wj3vQn0ggFT4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);